/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;
import java.util.Optional;
import javax.swing.table.DefaultTableModel;
import model.dao.ProdutoDAOImpl;
import model.entity.Produto;

/**
 *
 * @author ander
 */
public class ListarProdutosPane extends javax.swing.JPanel {

    TelaPrincipal telaPrincipal;
    /**
     * Creates new form ListarProdutosPane
     */
    public ListarProdutosPane(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
        List<Produto> listaProdutos = produtoDAOImpl.findAll();
        for(Produto produto: listaProdutos) {
            model.addRow(new Object[] {produto.getId(), produto.getNome(), produto.getValor(), produto.getCategoria(), produto.getQtd_estoque()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "VALOR", "CATEGORIA", "ESTOQUE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(60);
            tabelaProdutos.getColumnModel().getColumn(1).setMinWidth(130);
            tabelaProdutos.getColumnModel().getColumn(2).setMaxWidth(80);
            tabelaProdutos.getColumnModel().getColumn(4).setMinWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        if(evt.getClickCount() == 2) {
            int linhaSelecionada = tabelaProdutos.getSelectedRow();
            if(linhaSelecionada != -1) {
                Long idSelecionado = (Long) tabelaProdutos.getValueAt(linhaSelecionada, 0);
                telaPrincipal.ativarEdicaoProduto(idSelecionado);
            }
        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
    ProdutoDAOImpl produtoDAOImpl = new ProdutoDAOImpl();
}
