package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.dao.CategoriaDAOImpl;
import model.entity.Categoria;

public class ListarCategoriasPane extends javax.swing.JPanel {

    private final TelaPrincipal telaPrincipal;
    /**
     * Creates new form ListarCategoriasPane
     */
    public ListarCategoriasPane(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        DefaultTableModel model = (DefaultTableModel) tabelaCategorias.getModel();
        List<Categoria> listaCategorias = categoriaDAOImpl.findAll();
        for(Categoria categoria: listaCategorias) {
            model.addRow(new Object[] {categoria.getId(), categoria.getNome()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategorias = new javax.swing.JTable();

        tabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCategorias);
        if (tabelaCategorias.getColumnModel().getColumnCount() > 0) {
            tabelaCategorias.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCategoriasMouseClicked
        if(evt.getClickCount() == 2) {
            int linhaSelecionada = tabelaCategorias.getSelectedRow();
            if(linhaSelecionada != -1) {
                Long idSelecionado = (Long) tabelaCategorias.getValueAt(linhaSelecionada, 0);
                telaPrincipal.ativarEdicaoCategoria(idSelecionado);
            }
        }
    }//GEN-LAST:event_tabelaCategoriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCategorias;
    // End of variables declaration//GEN-END:variables
    private final CategoriaDAOImpl categoriaDAOImpl = new CategoriaDAOImpl();
}
