package view;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.dao.ReservaDAOImpl;
import model.entity.Reserva;

public class ListarReservasPane extends javax.swing.JPanel {

    private final TelaPrincipal telaPrincipal;
    /**
     * Creates new form ListarReservasPane
     */
    public ListarReservasPane(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        DefaultTableModel model = (DefaultTableModel) tabelaReservas.getModel();
        List<Reserva> listaReservas = reservaDAOImpl.findAllOrderByData();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (Reserva reserva: listaReservas){
            String dataFormatada = reserva.getDataReserva().format(formatter);
            model.addRow(new Object[] {reserva.getId(), reserva.getCliente().getNome(), reserva.getCliente().getCpf(), reserva.getQuadra().getNome(), reserva.getHorario(), dataFormatada});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReservas = new javax.swing.JTable();

        tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "QUADRA", "HORÁRIO", "DATA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaReservas);
        if (tabelaReservas.getColumnModel().getColumnCount() > 0) {
            tabelaReservas.getColumnModel().getColumn(0).setMaxWidth(60);
            tabelaReservas.getColumnModel().getColumn(1).setMinWidth(180);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaReservasMouseClicked
        if(evt.getClickCount() == 2) {
            int linhaSelecionada = tabelaReservas.getSelectedRow();
            if (linhaSelecionada != -1) {
                Long idSelecionado = (Long) tabelaReservas.getValueAt(linhaSelecionada, 0);
                telaPrincipal.ativarEdicaoReserva(idSelecionado);
            }
        }
    }//GEN-LAST:event_tabelaReservasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaReservas;
    // End of variables declaration//GEN-END:variables
    private final ReservaDAOImpl reservaDAOImpl = new ReservaDAOImpl();
}
